[repository]
name = "hyprexpo"
authors = ["sandwich.farm"]

[hyprexpo]
description = "hyprexpo+ — keyboard selection, labels, gaps, and Hyprland-style borders"
authors = ["sandwich"]
output = "hyprexpo.so"
build = [
"make all"
]

since_hyprland = 6066